const SESSION_ID = ""
const GITHUB_USER_NAME = ""
const GITHUB_AUTH_TOKEN = ""
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}