const SESSION_ID = "SADIYA-MD=vowQUQoS#vvFBhhLUwAvNrmJkTXj-meQaPUVry7KFH98gKwQ1FHM"
const GITHUB_USER_NAME = "vghdse"
const GITHUB_AUTH_TOKEN = "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"
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}
